extraObjects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: external-traefik
      namespace: traefik
    spec:
      ports:
        - port: 80
          targetPort: 80
          name: http
        - port: 443
          targetPort: 443
          name: https

  - apiVersion: v1
    kind: Endpoints
    metadata:
      name: external-traefik
      namespace: traefik
    subsets:
      - addresses:
          - ip: 192.168.27.249 # Replace with your external Traefik's IP
        ports:
          - port: 80
            name: http
          - port: 443
            name: https

  - apiVersion: traefik.io/v1alpha1
    kind: ServersTransport
    metadata:
      name: insecure
      namespace: traefik
    spec:
      insecureSkipVerify: true

  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: catch-all-fallback
      namespace: traefik
    spec:
      entryPoints:
        - websecure
        - webinternal
      routes:
        - match: PathPrefix(`/`)
          kind: Rule
          priority: 1
          services:
            - name: external-traefik
              port: 443
              scheme: https # Forward as HTTPS
              passHostHeader: true
              serversTransport: insecure

  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: minio
      namespace: traefik
    spec:
      entryPoints:
        - websecure
        - webinternal
      routes:
        - match: Host(`s3.max06.net`)
          kind: Rule
          services:
            - name: syno
              port: 9000
              passHostHeader: true

  - apiVersion: v1
    kind: Service
    metadata:
      name: syno
      namespace: traefik
    spec:
      ports:
        - port: 9000
          targetPort: 9000
          name: http

  - apiVersion: v1
    kind: Endpoints
    metadata:
      name: syno
      namespace: traefik
    subsets:
      - addresses:
          - ip: 192.168.27.10
        ports:
          - port: 9000
            name: http

  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: proxmox
      namespace: traefik
      annotations:
        external-dns.alpha.kubernetes.io/target: 192.168.30.242
    spec:
      entryPoints:
        - webinternal
      routes:
        - match: Host(`proxmox.max06.net`)
          kind: Rule
          services:
            - name: proxmox
              port: 8006
              scheme: https                    # Add this
              passHostHeader: false            # Change to true
              serversTransport: insecure

  - apiVersion: v1
    kind: Service
    metadata:
      name: proxmox
      namespace: traefik
    spec:
      ports:
        - port: 8006
          targetPort: 8006
          name: frontend
          protocol: TCP                        # Explicitly set protocol

  - apiVersion: discovery.k8s.io/v1
    kind: EndpointSlice
    metadata:
      name: proxmox
      namespace: traefik
      labels:
        kubernetes.io/service-name: proxmox
    addressType: IPv4
    ports:
      - name: frontend
        protocol: TCP
        port: 8006
    endpoints:
      - addresses:
          - "192.168.27.203"
        conditions:
          ready: true          # ADD THIS