environments:
  default:
    values:
      - repoUrl: https://github.com/max06/deployments
      - baseDir: clusters
  testing:
    values:
      - repoUrl: https://github.com/max06/deployments
      - baseDir: testing
---
helmfiles:
  - path: '{{ if eq .Environment.Name "default" }}clusters{{ else }}testing/{{ end }}/in-cluster/apps/argocd/helmfile.yaml'

repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
releases:
  - name: root
    namespace: argocd
    chart: argo/argocd-apps
    values:
      - appSets.yaml.gotmpl
      - repoUrl: https://github.com/max06/deployments
