apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=invalid"]
  generators:
    # Cluster/Apps
    - matrix:
        generators:
          - matrix:
              generators:
                - clusters:
                    values:
                      clusterGroup: "{{ or .metadata.labels.clusterGroup nil }}"
                      clusterName: "{{ or .metadata.labels.clusterId .name }}"
                - git:
                    repoURL: https://github.com/max06/deployments
                    revision: HEAD
                    directories:
                      - path: "clusters/{{ .values.clusterGroup }}/{{ .values.clusterName }}/apps/*"
                      - path: "clusters/{{ .values.clusterName }}/apps/*"

          - git:
              repoURL: https://github.com/max06/deployments
              revision: HEAD
              files:
                - path: "{{ .path.path }}/config.yaml"
              pathParamPrefix: appConfig

  template:
    metadata:
      name: "{{ .values.clusterName }}-{{ .path.basename }}"
    spec:
      destination:
        server: "{{ .server }}"
        namespace: "{{ .path.basename }}"
      project: default
      source:
        chart: hello-world
        repoURL: https://helm.github.io/examples
        targetRevision: 0.1.0
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

  # generators:
  #   - matrix:
  #       generators:
  #         # ClusterGroups
  #         - git:
  #             repoURL: https://github.com/max06/deployments
  #             revision: HEAD
  #             files:
  #               - path: "clusters/*/"
  #             pathParamPrefix: clusterGroup

  #         # Cluster/Apps
  #         - matrix:
  #             generators:
  #               # Cluster in clusterGroup
  #               - clusters:
  #                   selector:
  #                     matchLabels:
  #                       argocd.argoproj.io/secret-type: cluster
  #                       clusterGroup: "{{ .clusterGroupName }}"
  #               # git generator, 'child' #1
  #               - git:
  #                   repoURL: https://github.com/max06/deployments
  #                   revision: HEAD
  #                   files:
  #                     - path: "clusters/{{ .clusterGroupName }}/{{ .name }}/apps/*"
