apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cyrannus
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # Cluster/Apps
    - matrix:
        generators:
          - clusters: {}
          - git:
              repoURL: https://github.com/max06/deployments
              revision: HEAD
              directories:
                - path: "clusters/*/{{ .name }}/apps/*"
                - path: "clusters/{{ .name }}/apps/*"

  template:
    metadata:
      name: "{{ .name }}-{{ .path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/max06/deployments
        targetRevision: HEAD
        path: "{{ .path }}"
        kustomize:
          enableHelm: true
      destination:
        server: "{{ .server }}"
        namespace: "{{ .path.basename }}"
