---
helmfiles:
  - path: ../../../../../apps/home-assistant/helmfile.yaml
    values:
      - primary_domain: '{{ "ref+sops://values.sops.yaml#primary_domain" | fetchSecretValue }}'
      - ingress:
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: traefik-public@kubernetescrd
