apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../apps/argocd/manifests

helmCharts:
  - name: argocd
    valuesInline:
      global:
        additionalLabels:
          argocd.argoproj.io/instance: helios-argocd
