repositories:
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/

releases:
  - name: external-dns
    chart: external-dns/external-dns
    version: 1.17.0
    namespace: external-dns
    values:
      # - image:
      #     tag: v0.18.0
      - provider:
          name: pihole

        sources:
          - service
          - ingress
          - traefik-proxy
        registry: noop
        extraArgs:
          - "--pihole-api-version=6"
        env:
          - name: EXTERNAL_DNS_PIHOLE_SERVER
            value: http://pihole-web.pihole.svc.cluster.local
          - name: EXTERNAL_DNS_PIHOLE_PASSWORD
            value: "{{ .Values.pihole_password }}"
        logLevel: debug
