deployment:
  replicas: 2
#   resources:
#     requests:
#       cpu: 100m
#       memory: 128Mi
#     limits:
#       cpu: 300m
#       memory: 256Mi

ingressRoute:
  dashboard:
    enabled: true

# providers:
#   kubernetesCRD:
#     enabled: true
#   kubernetesIngress:
#     enabled: true

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    middlewares:
      - traefik-internal@kubernetescrd

#     port: 443
#     expose: true
#     exposedPort: 443
#     protocol: TCP

service:
  type: LoadBalancer
  spec:
    loadBalancerClass: io.cilium/l2-announcer
  annotations:
    "lbipam.cilium.io/ips": "192.168.30.240"
    "service.cilium.io/type": "LoadBalancer"
    "service.cilium.io/forwarding-mode": "dsr"
# securityContext:
#   capabilities:
#     drop: [ALL]
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 65532

logs:
  access:
    # -- To enable access logs
    enabled: true
