deployment:
  replicas: 2
#   resources:
#     requests:
#       cpu: 100m
#       memory: 128Mi
#     limits:
#       cpu: 300m
#       memory: 256Mi

ingressRoute:
  dashboard:
    enabled: true

# providers:
#   kubernetesCRD:
#     enabled: true
#   kubernetesIngress:
#     enabled: true

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
    expose:
      default: false
      public: true
  websecure:
    expose:
      default: false
      public: true
  webinternal:
    port: 8444
    exposedPort: 443
    expose:
      default: true
      public: false
    tls:
      enabled: true
    middlewares:
      - traefik-internal@kubernetescrd

#     port: 443
#     expose: true
#     exposedPort: 443
#     protocol: TCP

service:
  type: LoadBalancer
  spec:
    loadBalancerClass: io.cilium/l2-announcer
  annotations:
    "service.cilium.io/type": "LoadBalancer"
  additionalServices:
    public:
      type: LoadBalancer
      labels:
        traefik-service-label: internal
      annotations:
        "lbipam.cilium.io/ips": "192.168.30.240"
        "service.cilium.io/type": "LoadBalancer"
      spec:
        loadBalancerClass: io.cilium/l2-announcer

logs:
  access:
    # -- To enable access logs
    enabled: true
