apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-to-argocd-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rancher-to-argocd-controller
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/max06/deployments
    targetRevision: main
    path: clusters/in-cluster/apps/rancher-to-argocd-controller
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
