apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
spec:
  infra:
    nodePlacement:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
