sources:
  - repoURL: https://mojo2600.github.io/pihole-kubernetes/
    chart: pihole
    targetRevision: 2.29.1
    helm:
      valueFiles:
        - values.yaml
      ignoreMissingValueFiles: true
      releaseName: pihole
