repositories:
  - name: pihole
    url: https://mojo2600.github.io/pihole-kubernetes/

releases:
  - name: pihole
    chart: pihole/pihole
    version: 2.31.0
    values:
      - replicaCount: 1
        serviceDhcp:
          enabled: false
        serviceDns:
          type: LoadBalancer
          mixedService: true
          annotations:
            "lbipam.cilium.io/ips": "192.168.30.241"
          externalTrafficPolicy: Cluster
        doh:
          enabled: true
        extraEnvVars:
          FTLCONF_dns_listeningMode: all
        persistentVolumeClaim:
          enabled: true
        image:
          tag: "2025.06.2"
