repositories:
  - name: pihole
    url: https://mojo2600.github.io/pihole-kubernetes/

releases:
  - name: pihole
    chart: pihole/pihole
    version: 2.29.1
    values:
      - replicaCount: 2
        serviceDhcp:
          enabled: false
        serviceDns:
          type: LoadBalancer
          mixedService: true
          annotations:
            "lbipam.cilium.io/ips": "192.168.30.241"
        doh:
          enabled: true
        extraEnvVars:
          FTLCONF_dns_listeningMode: all
