apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: pihole
    repo: https://mojo2600.github.io/pihole-kubernetes/
    version: 2.9.3
    releaseName: pihole
    namespace: pihole
