# yaml-language-server: $schema=https://www.schemastore.org/helmfile.json
---
namespace: external-services

helmfiles:
  - path: ../../../../../apps/external-service/helmfile.yaml
    values:
      - name: proxmox
        target: srv-pm01.srv.hive.internal
  - path: ../../../../../apps/external-service/helmfile.yaml
    values:
      - name: somethingelse
        target: somethingelse.srv.hive.internal
