repositories:
  - name: pajikos
    url: http://pajikos.github.io/home-assistant-helm-chart/

releases:
  - name: home-assistant
    chart: pajikos/home-assistant
    version: 0.3.4
    namespace: home-assistant
    values:
      - persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 10Gi
          storageClass: ""
        addons:
          codeserver:
            enabled: true
        ingress:
          enabled: true
          tls:
            - hosts:
                - home.{{ .Values.primary_domain }}
              secretName: 'wildcard-{{ .Values.primary_domain | replace "." "-" }}-tls'
          hosts:
            - host: home.{{ .Values.primary_domain }}
              paths:
                - path: /
