global:
  additionalLabels:
    argocd.argoproj.io/instance: argocd
server:
  configEnabled: true
  config:
    repositories: []
  additionalApplications: []
  additionalProjects: []
extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: repo-github
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
        argocd.argoproj.io/instance: argocd
    stringData:
      type: git
      url: https://github.com/max06/deployments
  - apiVersion: v1
    kind: Secret
    metadata:
      name: repo-helm
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
        argocd.argoproj.io/instance: argocd
    stringData:
      type: helm
      name: max06
      url: https://max06.github.io/deployments
