encryption_key: ENC[AES256_GCM,data:99fO6n2rAGpKbTUfxcPBAV6x4nkJ2Qjk3oMOVPwTQg0=,iv:S06MDh7BUFefR4VtUhNzYWSTY9OtB6Gh7Sl9ka4/UdA=,tag:/gyVhEZ/rBPWRdv6ZARjNw==,type:str]
license_activation_key: ENC[AES256_GCM,data:iL3OWhioJXIBmQuiXPf7j19ECAdey59Xp+NZb1gSb1OCc+i3,iv:B+Drku+6lqF7TMQSLXBCNSHHTaZ/sqWsmRBZtFD8yCk=,tag:RTS5j8ArJ0FLKg+wk2IFww==,type:str]
sops:
    age:
        - recipient: age1y7udc7lr39ekhxrdn54lrslmktzduw3594jdc9c9pgg6ej79r9jszgm4sw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaVB2STJ4emNZVUhKQ3RL
            Y1FhS0NMaFM3Mlh3NTI1R3dDKytObDN5a2pvCk5LMG1Mc3RoUTYxTFc1S1IyRVZP
            VTdCb1ZHZW13RjMwSEs3eWRUZlNFUkkKLS0tIDdKOVdJdTZxd2ptRm44UkNYalEw
            VkZlT2JnSGRNUTR5VVdDQzJkZ1dnRGcKZsU6LZxkUWFBmK0EiGpqdnGIG5gAGIsd
            KbbV7Vtbm3c7l0yVekWCoVinwBfPK8H0LiELG5RkRRsctmJcO+5/ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pr4x8umup43rypmp3z4u2t504q3cyhf9tqzuzugwh7ay0r0umq5qzxkrfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aU43NWRXd3lqVFA4QW5l
            R1I4Mi84b3FVYnh5dktPc290MTYyQWgzU1ZBCnBDOGkxcXk3blRmUGhQVXoyM2l5
            V3dHbE54VHRuckxjWm1YcEFkOTVReUUKLS0tIFVvb1lWL29STWxhMTNaQk1CcW9l
            b2dGUlg3QlNHTFF2YlZJY1I3by9BUG8KlElzij47wkW3mTx1DOgoKXSs18fAfMDi
            u+oXTrXo29Yrkq57EM7ouCC9kjh9yMvGnx95fTlCF7WesmwwLYNS+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kjh0myksatp45tqsvk59zsgh4kyfhm5q4u97jcwaww0vm74l4fjsad0epw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eTNzVDl6WGJnTjJ1bStI
            RW5IQjlTZmtFQjR5VjA4Z09TSWwrMm5pMzJNCkVUSmlaYVBnSWNaSGlJU3RCL1RZ
            N1podEVMdUxmMHFEVzEwWWxmaWozNm8KLS0tIGFRZEk2SHE4TklJUWhDN0Ezc3RT
            Y1dLR0JNWnpsMmxyTWFldE9iZ0U1UjQK0fqusPHgXrY8MkoUCskVY0GuW/uVSneQ
            3gjVUgsfqozaC2+jhJjiHnzDSG0xdgf/BxAZ6PQHhVVpV2UlyXQmlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T19:47:07Z"
    mac: ENC[AES256_GCM,data:zOJ0Oq2ZlqqLRtYJ2HZSGsFg/g8BPsnpwYyWF/Jb3cRiuIhpIUZYm4FsBPrZyxuABZAJmT2RT+v0q5XUFOB3Lw1SYHWkCrJ7Qg7mVJOh109KdFvPRQcbPiKclbfvuZOFlVrETWb8bhauDxSXGHYZg3yorS50OUhWvtFfM2nN0EM=,iv:HknL5xr5zj4vzn9PaugO/CUc2GNNavu4bC/gHxJkWys=,tag:XkTH9ertcr3p2nrM4SVqew==,type:str]
    pgp:
        - created_at: "2026-05-10T19:47:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3l5YWXaEkdcAQ//TlKF64kYDLzhABeQIzKM0mIEwpkVp07IvN5yGKGpjdG/
            4nTInK6IlS4kHIeI/8VzQ6HAPpnuRqGyiR2QCbO9JmqU8wtxVCRAuwb9hb0SCcYG
            dTnxJFUTWC1kK/pPSjcfpN/iubAYIQ80rXnghsNCvxfP33tZVc7QunC4FY/XOTLR
            ahQJ1+x+wMUtHVFR+zv4P6+SfzzkePr+FME90OjjM8bdMP2yMfA4SoYp8JybasAL
            JxhDRsjlXz7HP/YO4zTeRfBr6phvRvM+1GB5gFL1Ol4Mtk5EgGkw44cW18k+fvFx
            aSOvSyl4KWyFkeyIvlM6tLDzvJUjaUQc8h+SO/yXOVzCGM0ZNRGWEPcNg33WQn27
            I8XlhR1T9Z4TMnpIQ2u4wkROh7RZUaFtdaCLZAJHPhMELPyp/GS/L0CIxOFCOjSz
            WHa8dGMUNs3rmpULy9GT7hqp0fpfcrj7/hhtz6FZ7A6TGejCU0TXb8aDHj1GYli4
            cxJuizHptwwY1ktVFwilczgeyWNUGpPL6Oo89IF8v6pEiyk8/taC45lTnax8ITAY
            F2e5WdKVRByUx/Yz8HtLvwBHSeF/C2RzkUZ5vrr32IWcVa+ZiAWCrKVLNhPVSnnY
            qkxZ/YWlidFznLjRfsGe33o/PmfCC0VptwMjV0HkHKSoe9+aC6peZNH9MXIH8DjS
            XgEpD80WRR+DX72z38Qo894iodS69nVRjWBjz8/+MNBXS8LTHaKD7MssdzNAl1wl
            2GOSy6Mg0h8eqIqRxWK3Gy0NhpMKX7k3nCnsKzBd0Vs1H1CGmcXVzznzUk9Sh9s=
            =HViC
            -----END PGP MESSAGE-----
          fp: FAE80AAB28045B8BE8603DBD07E86793BA50B1F5
    unencrypted_suffix: _unencrypted
    version: 3.12.2
