name: Helm charts

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest 
    name: Test helm chart
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: /apps
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
