---
repositories:
  - name: argo-helm
    url: https://argoproj.github.io/argo-helm
releases:
  - name: argocd
    chart: argo-helm/argo-cd
    version: 8.6.4
    namespace: argocd
    values:
      - global:
          domain: 'ci.{{ .StateValues | get "primary_domain" }}'
      - values.yaml
    strategicMergePatches:
      - patches/repo-server.yaml
    transformers:
      - apiVersion: builtin
        kind: LabelTransformer
        metadata:
          name: notImportantHere
        labels:
          argocd.argoproj.io/instance: in-cluster-argocd
        fieldSpecs:
          - path: metadata/labels
            create: true
